version: '3.1'
services:
  stats-server:
    build: ./stat-service/server
    image: stat-service-img
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics

  stats-db:
    image: postgres:14-alpine
    container_name: statistics
    ports:
      - "6451:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service-img
    container_name: ewm-service
